export function createKeywordsColumns(platform) {
    console.log('platform', platform)
    if (platform === 'douyin') {
        return [
            { "title": "站内唯一视频id", "key": "itemId" },
            { "title": "视频发表用户名称", "key": "userName" },
            { "title": "视频发表用户id", "key": "userItemId" },
            { "title": "视频发表时间", "key": "publishTimestamp" },
            { "title": "视频链接", "key": "videoUrl", ellipsis: true },
            { "title": "视频时长", "key": "videoDuration" },
            { "title": "视频标题", "key": "title" },
            { "title": "视频内容", "key": "content" },
            { "title": "视频内容情感", "key": "sentiment" },
            { "title": "视频拍摄地点打卡人数", "key": "locationVisitUserCnt" },
            { "title": "视频互动量", "key": "interactionCnt" },
            { "title": "视频收藏数", "key": "collectionCnt" },
            { "title": "视频点赞数", "key": "likeCnt" },
            { "title": "视频分享数(分享转发)", "key": "shareCnt" },
            { "title": "转发数(分享转发)", "key": "repostCnt" },
            { "title": "视频播放量", "key": "viewCnt" },
            { "title": "视频评论数", "key": "commentCnt" },
            { "title": "封面图片url", "key": "thumbnailUrl", ellipsis: true },
            { "title": "是否私密视频", "key": "isPrivate" },
            { "title": "参与的挑战列表", "key": "challenges" },
            { "title": "是否精选", "key": "isRecom" },
            { "title": "视频播放链接", "key": "videoPlayUrls", ellipsis: true },
            { "title": "音频播放链接", "key": "audioPlayUrls", ellipsis: true },
            { "title": "发表视频地址", "key": "address" },
            { "title": "发表视频省份", "key": "province" },
            { "title": "发表视频城市", "key": "city" },
            { "title": "发表视频行政区", "key": "district" },
            { "title": "视频带货标题", "key": "commodityTitle" },
            { "title": "提到标签列表", "key": "mentionLabels" },
            { "title": "声量类型", "key": "volumeType" },
            { "title": "平台广告类型(平台定义的)", "key": "platformIsAd" },
            { "title": "抖音主贴分类", "key": "postType" },
            { "title": "抖音sec_uid", "key": "secUserItemId", ellipsis: true },
            { "title": "发文时用户粉丝数", "key": "userFollowerCnt" },
            { "title": "贴纸id", "key": "stickerId" },
            { "title": "贴纸名称", "key": "stickerName" },
            { "title": "音乐标题", "key": "musicName" },
            { "title": "图片链接列表", "key": "picUrls", ellipsis: true },
            { "title": "视频状态", "key": "postState" },
            { "title": "贴纸分类", "key": "stickerType" },
            { "title": "视频中文字", "key": "textInVideoContent", ellipsis: true },
            { "title": "发表视频地理位置名称", "key": "poiName" },
            { "title": "私密赞", "key": "privateLikeCnt" },
            { "title": "sec_item id", "key": "secItemId" },
            { "title": "采集时间", "key": "updateTimestamp" },
            { "title": "用户头像链接", "key": "avatarUrl", ellipsis: true }
        ]
    } else if (platform === 'bilibili') {
        return [
            { "title": "站内唯一视频/动态id", "key": "itemId" },
            { "title": "分类id", "key": "catId" },
            { "title": "视频发表用户名称", "key": "userName" },
            { "title": "视频发表用户id", "key": "userItemId" },
            { "title": "视频发表时间", "key": "publishTimestamp" },
            { "title": "视频链接", "key": "url", ellipsis: true },
            { "title": "视频标题", "key": "title" },
            { "title": "视频简介", "key": "content" },
            { "title": "视频播放量", "key": "viewCnt" },
            { "title": "视频点赞数", "key": "likeCnt" },
            { "title": "视频反对数", "key": "dislikeCnt" },
            { "title": "视频分享数", "key": "shareCnt" },
            { "title": "视频转发数(分享转发)", "key": "repostCnt" },
            { "title": "视频评论数", "key": "commentCnt" },
            { "title": "弹幕数", "key": "barrageCnt" },
            { "title": "硬币数", "key": "coinCnt" },
            { "title": "收藏数", "key": "collectionCnt" },
            { "title": "互动量", "key": "interactionCnt" },
            { "title": "视频封面缩略图链接", "key": "thumbnailUrl", ellipsis: true },
            { "title": "音频播放链接", "key": "audioPlayUrls" },
            { "title": "视频时长", "key": "videoDuration" },
            { "title": "是否原创", "key": "isOriginal" },
            { "title": "视频标签列表", "key": "videoLabels" },
            { "title": "面包屑导航描述", "key": "navigationDesc" },
            { "title": "视频内容情感", "key": "sentiment" },
            { "title": "视频IP归属地", "key": "ipLocation" },
            { "title": "主贴类型", "key": "postType" },
            { "title": "扩展id", "key": "extId" },
            { "title": "原贴内容", "key": "srcContent" },
            { "title": "原贴标题", "key": "srcTitle" },
            { "title": "原贴id", "key": "srcId", ellipsis: true },
            { "title": "原贴url", "key": "srcUrl", ellipsis: true },
            { "title": "原贴用户名", "key": "srcUserName" },
            { "title": "原贴用户id", "key": "srcUserItemId" },
            { "title": "主贴细分类型", "key": "postDetailType" },
            { "title": "合集id", "key": "seriesId" },
            { "title": "合集名称", "key": "seriesName" },
            { "title": "图片链接列表", "key": "picUrls", ellipsis: true },
            { "title": "话题列表", "key": "topics" },
            { "title": "播放时长", "key": "playDuration" },
            { "title": "采集时间", "key": "updateTimestamp" },
            { "title": "用户头像链接", "key": "avatarUrl", ellipsis: true }
        ]          
    }
}