export function createUserColumns(platform) {
  if (platform === 'douyin') {
    return [
        { title: '站内唯一用户id', key: 'itemId' },
        { title: '用户注册id', key: 'registerId' },
        { title: '用户名称', key: 'userName' },
        { title: ' 用户性别 ', key: 'gender' },
        { title: ' 用户头像 ', key: 'avatarUrl', ellipsis: true },
        { title: ' 用户对外分享链接 ', key: 'shareUrl', ellipsis: true },
        { title: ' 出生日期 ', key: 'birthday' },
        { title: ' 出生年份 ', key: 'birthYear' },
        { title: ' 用户注册时间 ', key: 'registerTimestamp' },
        { title: ' 用户所在省 ', key: 'province' },
        { title: ' 用户所在市 ', key: 'city' },
        { title: ' 城市等级 ', key: 'cityLevel' },
        { title: ' 用户简介 ', key: 'userDesc', ellipsis: true },
        { title: ' 是否认证用户 ', key: 'isVerified' },
        { title: ' 认证类型 ', key: 'verifiedType' },
        { title: ' 认证原因 ', key: 'verifiedReason' },
        { title: ' 用户关注数 ', key: 'friendCnt' },
        { title: ' 用户粉丝数 ', key: 'followerCnt' },
        { title: ' 用户发表视频数 ', key: 'videoCnt' },
        { title: ' 用户获得点赞 ', key: 'likeCnt' },
        { title: ' 用户收藏视频数 ', key: 'collectionCnt' },
        { title: ' 用户星座 ', key: 'constellation' },
        { title: ' 关注列表 ', key: 'friends', ellipsis: true },
        { title: ' 粉丝列表 ', key: 'followers', ellipsis: true },
        { title: ' 用户参与挑战列表 ', key: 'challenges', ellipsis: true },
        { title: ' 用户喜欢视频列表 ', key: 'likeVideoItemIds', ellipsis: true },
        { title: ' 用户联系信息 (手机 / 电话)', key: 'contactInfo' },
        { title: ' 用户地址 ', key: 'address' },
        { title: ' 抖音 sec_uid', key: 'secUserItemId', ellipsis: true },
        { title: ' 用户 IP 归属地 ', key: 'ipLocation' },
        { title: ' 是否入驻 ', key: 'isStarAtlas' },
        { title: 'MCN 机构名称 ', key: 'mcn' },
        { title: ' 采集时间 ', key: 'updateTimestamp' }
    ]
  } else if (platform === 'bilibili') {
    return [
        {title: ' 站内唯一用户 id', key: 'userId'},
        { title: ' 用户名称 ', key: 'userName' },
        { title: ' 用户头像链接 ', key: 'avatarUrl' },
        { title: ' 用户主页链接 ', key: 'itemUrl' },
        { title: ' 出生日期 ', key: 'birthday' },
        { title: ' 是否有粉丝徽章 ', key: 'hasFollowerBadge' },
        { title: ' 用户粉丝数 ', key: 'followerCnt' },
        { title: ' 用户关注数 ', key: 'friendCnt' },
        { title: ' 用户性别 ', key: 'gender' },
        { title: ' 用户等级 ', key: 'userLevel' },
        { title: ' 用户获取点赞数 ', key: 'likeCnt' },
        { title: ' 用户当月获取充电数 ', key: 'supportBatteryMonthCnt' },
        { title: ' 用户获取充电总数 ', key: 'supportBatteryTotalCnt' },
        { title: ' 认证类型 ', key: 'verifiedType' },
        { title: ' 用户认证原因 ', key: 'verifiedReason' },
        { title: ' 用户视频获得播放数 ', key: 'videoPlayCnt' },
        { title: ' 用户签名描述 ', key: 'userDesc' },
        { title: ' 是否被关小黑屋 ', key: 'isBlocked' },
        { title: ' 用户主页背景图片链接 ', key: 'bgPicUrl' },
        { title: ' 是否 vip', key: 'isVip' },
        { title: 'vip 类型 ', key: 'vipType' },
        { title: ' 关注列表 ', key: 'friends' },
        { title: ' 点赞视频列表 ', key: 'likeVideoItemIds' },
        { title: ' 投币视频列表 ', key: 'coinVideoItemIds'},
        { title: ' 收藏视频列表 ', key: 'collectVideoItemIds' },
        { title: ' 用户主动点赞视频数 ', key: 'likeVideoCnt' },
        { title: ' 用户主动收藏视频数 ', key: 'collectVideoCnt' },
        { title: ' 用户发表视频数（投稿视频数）', key: 'postVideoCnt' },
        { title: ' 用户发表主题贴数 ', key: 'postCnt' },
        { title: ' 用户标签列表 ', key: 'userTags' },
        { title: ' 用户订阅番剧列表 ', key: 'subscribeAnimeItemIds' },
        { title: ' 用户订阅漫画列表 ', key: 'subscribeCartoonItemIds' },
        { title: ' 用户订阅影视列表 ', key: 'subscribeCinemaItemIds' },
        { title: ' 用户订阅的标签列表 ', key: 'subscribeTags' },
        { title: ' 用户文章获得阅读数 ', key: 'postViewCnt' },
        { title: ' 获得充电用户列表 ', key: 'supportBatteryUserItemIds' },
        { title: ' 用户 IP 归属地 ', key: 'ipLocation' },
        { title: ' 是否入驻 ', key: 'isStarAtlas' },
        { title: 'MCN 机构的名称 ', key: 'mcn' },
        { title: ' 分类 id', key: 'catId' },
        { title: ' 采集时间 ', key: 'updateTimestamp' }
    ]
  }
}