// 抖音作者/视频字段名映射
export const douyinKeywordsHeaderMap = {
    'itemId': '站内唯一视频id',
    'userName': '视频发表用户名称',
    'userItemId': '视频发表用户id',
    'publishTimestamp': '视频发表时间',
    'videoUrl': '视频链接',
    'videoDuration': '视频时长',
    'title': '视频标题',
    'content': '视频内容',
    'sentiment': '视频内容情感',
    'locationVisitUserCnt': '视频拍摄地点打卡人数',
    'interactionCnt': '视频互动量',
    'collectionCnt': '视频收藏数',
    'likeCnt': '视频点赞数',
    'shareCnt': '视频分享数(分享转发)',
    'repostCnt': '转发数(分享转发)',
    'viewCnt': '视频播放量',
    'commentCnt': '视频评论数',
    'thumbnailUrl': '封面图片url',
    'isPrivate': '是否私密视频',
    'challenges': '参与的挑战列表',
    'isRecom': '是否精选',
    'videoPlayUrls': '视频播放链接',
    'audioPlayUrls': '音频播放链接',
    'address': '发表视频地址',
    'province': '发表视频省份',
    'city': '发表视频城市',
    'district': '发表视频行政区',
    'commodityTitle': '视频带货标题',
    'mentionLabels': '提到标签列表',
    'volumeType': '声量类型',
    'platformIsAd': '平台广告类型(平台定义的)',
    'postType': '抖音主贴分类',
    'secUserItemId': '抖音sec_uid',
    'userFollowerCnt': '发文时用户粉丝数',
    'stickerId': '贴纸id',
    'stickerName': '贴纸名称',
    'musicName': '音乐标题',
    'picUrls': '图片链接列表',
    'postState': '视频状态',
    'stickerType': '贴纸分类',
    'textInVideoContent': '视频中文字',
    'poiName': '发表视频地理位置名称',
    'privateLikeCnt': '私密赞',
    'secItemId': 'sec_item id',
    'updateTimestamp': '采集时间',
    'avatarUrl': '用户头像链接'
}

// B站作者/视频字段名映射
export const bilibiliKeywordsHeaderMap = {
    'itemId': '站内唯一视频/动态id',
    'catId': '分类id',
    'userName': '视频发表用户名称',
    'userItemId': '视频发表用户id',
    'publishTimestamp': '视频发表时间',
    'url': '视频链接',
    'title': '视频标题',
    'content': '视频简介',
    'viewCnt': '视频播放量',
    'likeCnt': '视频点赞数',
    'dislikeCnt': '视频反对数',
    'shareCnt': '视频分享数',
    'repostCnt': '视频转发数(分享转发)',
    'commentCnt': '视频评论数',
    'barrageCnt': '弹幕数',
    'coinCnt': '硬币数',
    'collectionCnt': '收藏数',
    'interactionCnt': '互动量',
    'thumbnailUrl': '视频封面缩略图链接',
    'audioPlayUrls': '音频播放链接',
    'videoDuration': '视频时长',
    'isOriginal': '是否原创',
    'videoLabels': '视频标签列表',
    'navigationDesc': '面包屑导航描述',
    'sentiment': '视频内容情感',
    'ipLocation': '视频IP归属地',
    'postType': '主贴类型',
    'extId': '扩展id',
    'srcContent': '原贴内容',
    'srcTitle': '原贴标题',
    'srcId': '原贴id',
    'srcUrl': '原贴url',
    'srcUserName': '原贴用户名',
    'srcUserItemId': '原贴用户id',
    'postDetailType': '主贴细分类型',
    'seriesId': '合集id',
    'seriesName': '合集名称',
    'picUrls': '图片链接列表',
    'topics': '话题列表',
    'playDuration': '播放时长',
    'updateTimestamp': '采集时间',
    'avatarUrl': '用户头像链接'
}

// 根据平台获取作者/视频字段映射
export function getKeywordsHeaderMap(platform) {
    if (platform === 'douyin') {
        return douyinKeywordsHeaderMap
    } else if (platform === 'bilibili') {
        return bilibiliKeywordsHeaderMap
    }
    return {}
}